//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public int KId { get; set; }
        public string Adıi { get; set; }
        public string Soyadi { get; set; }
        public string TC { get; set; }
        public string TelefonNo { get; set; }
        public string email { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
    }
}
